// flow-typed signature: 336907f5217c9e83146a2e722e8cabb6
// flow-typed version: <<STUB>>/farmhash_v^3.2.2/flow_v0.166.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'farmhash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'farmhash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'farmhash/index' {
  declare module.exports: $Exports<'farmhash'>;
}
declare module 'farmhash/index.js' {
  declare module.exports: $Exports<'farmhash'>;
}
