// flow-typed signature: 44a0a12a40c0985007d6865214630e15
// flow-typed version: <<STUB>>/ip-address_v8.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ip-address'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ip-address' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ip-address/dist/cjs/ip-address' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/address-error' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/common' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/ipv4' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/ipv6' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/v4/constants' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/v6/constants' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/v6/helpers' {
  declare module.exports: any;
}

declare module 'ip-address/dist/cjs/lib/v6/regular-expressions' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/ip-address' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/address-error' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/common' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/ipv4' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/ipv6' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/v4/constants' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/v6/constants' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/v6/helpers' {
  declare module.exports: any;
}

declare module 'ip-address/dist/esm/lib/v6/regular-expressions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ip-address/dist/cjs/ip-address.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/ip-address'>;
}
declare module 'ip-address/dist/cjs/lib/address-error.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/address-error'>;
}
declare module 'ip-address/dist/cjs/lib/common.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/common'>;
}
declare module 'ip-address/dist/cjs/lib/ipv4.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/ipv4'>;
}
declare module 'ip-address/dist/cjs/lib/ipv6.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/ipv6'>;
}
declare module 'ip-address/dist/cjs/lib/v4/constants.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/v4/constants'>;
}
declare module 'ip-address/dist/cjs/lib/v6/constants.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/v6/constants'>;
}
declare module 'ip-address/dist/cjs/lib/v6/helpers.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/v6/helpers'>;
}
declare module 'ip-address/dist/cjs/lib/v6/regular-expressions.js' {
  declare module.exports: $Exports<'ip-address/dist/cjs/lib/v6/regular-expressions'>;
}
declare module 'ip-address/dist/esm/ip-address.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/ip-address'>;
}
declare module 'ip-address/dist/esm/lib/address-error.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/address-error'>;
}
declare module 'ip-address/dist/esm/lib/common.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/common'>;
}
declare module 'ip-address/dist/esm/lib/ipv4.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/ipv4'>;
}
declare module 'ip-address/dist/esm/lib/ipv6.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/ipv6'>;
}
declare module 'ip-address/dist/esm/lib/v4/constants.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/v4/constants'>;
}
declare module 'ip-address/dist/esm/lib/v6/constants.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/v6/constants'>;
}
declare module 'ip-address/dist/esm/lib/v6/helpers.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/v6/helpers'>;
}
declare module 'ip-address/dist/esm/lib/v6/regular-expressions.js' {
  declare module.exports: $Exports<'ip-address/dist/esm/lib/v6/regular-expressions'>;
}
