// flow-typed signature: 4cda868eff711e0d60f39270d2396a75
// flow-typed version: <<STUB>>/logform_v^2.3.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'logform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'logform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'logform/align' {
  declare module.exports: any;
}

declare module 'logform/browser' {
  declare module.exports: any;
}

declare module 'logform/cli' {
  declare module.exports: any;
}

declare module 'logform/colorize' {
  declare module.exports: any;
}

declare module 'logform/combine' {
  declare module.exports: any;
}

declare module 'logform/dist/align' {
  declare module.exports: any;
}

declare module 'logform/dist/browser' {
  declare module.exports: any;
}

declare module 'logform/dist/cli' {
  declare module.exports: any;
}

declare module 'logform/dist/colorize' {
  declare module.exports: any;
}

declare module 'logform/dist/combine' {
  declare module.exports: any;
}

declare module 'logform/dist/errors' {
  declare module.exports: any;
}

declare module 'logform/dist/format' {
  declare module.exports: any;
}

declare module 'logform/dist' {
  declare module.exports: any;
}

declare module 'logform/dist/json' {
  declare module.exports: any;
}

declare module 'logform/dist/label' {
  declare module.exports: any;
}

declare module 'logform/dist/levels' {
  declare module.exports: any;
}

declare module 'logform/dist/logstash' {
  declare module.exports: any;
}

declare module 'logform/dist/metadata' {
  declare module.exports: any;
}

declare module 'logform/dist/ms' {
  declare module.exports: any;
}

declare module 'logform/dist/pad-levels' {
  declare module.exports: any;
}

declare module 'logform/dist/pretty-print' {
  declare module.exports: any;
}

declare module 'logform/dist/printf' {
  declare module.exports: any;
}

declare module 'logform/dist/simple' {
  declare module.exports: any;
}

declare module 'logform/dist/splat' {
  declare module.exports: any;
}

declare module 'logform/dist/timestamp' {
  declare module.exports: any;
}

declare module 'logform/dist/uncolorize' {
  declare module.exports: any;
}

declare module 'logform/errors' {
  declare module.exports: any;
}

declare module 'logform/examples/combine' {
  declare module.exports: any;
}

declare module 'logform/examples/filter' {
  declare module.exports: any;
}

declare module 'logform/examples/invalid' {
  declare module.exports: any;
}

declare module 'logform/examples/metadata' {
  declare module.exports: any;
}

declare module 'logform/examples/padLevels' {
  declare module.exports: any;
}

declare module 'logform/examples/volume' {
  declare module.exports: any;
}

declare module 'logform/format' {
  declare module.exports: any;
}

declare module 'logform/json' {
  declare module.exports: any;
}

declare module 'logform/label' {
  declare module.exports: any;
}

declare module 'logform/levels' {
  declare module.exports: any;
}

declare module 'logform/logstash' {
  declare module.exports: any;
}

declare module 'logform/metadata' {
  declare module.exports: any;
}

declare module 'logform/ms' {
  declare module.exports: any;
}

declare module 'logform/pad-levels' {
  declare module.exports: any;
}

declare module 'logform/pretty-print' {
  declare module.exports: any;
}

declare module 'logform/printf' {
  declare module.exports: any;
}

declare module 'logform/simple' {
  declare module.exports: any;
}

declare module 'logform/splat' {
  declare module.exports: any;
}

declare module 'logform/timestamp' {
  declare module.exports: any;
}

declare module 'logform/uncolorize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'logform/align.js' {
  declare module.exports: $Exports<'logform/align'>;
}
declare module 'logform/browser.js' {
  declare module.exports: $Exports<'logform/browser'>;
}
declare module 'logform/cli.js' {
  declare module.exports: $Exports<'logform/cli'>;
}
declare module 'logform/colorize.js' {
  declare module.exports: $Exports<'logform/colorize'>;
}
declare module 'logform/combine.js' {
  declare module.exports: $Exports<'logform/combine'>;
}
declare module 'logform/dist/align.js' {
  declare module.exports: $Exports<'logform/dist/align'>;
}
declare module 'logform/dist/browser.js' {
  declare module.exports: $Exports<'logform/dist/browser'>;
}
declare module 'logform/dist/cli.js' {
  declare module.exports: $Exports<'logform/dist/cli'>;
}
declare module 'logform/dist/colorize.js' {
  declare module.exports: $Exports<'logform/dist/colorize'>;
}
declare module 'logform/dist/combine.js' {
  declare module.exports: $Exports<'logform/dist/combine'>;
}
declare module 'logform/dist/errors.js' {
  declare module.exports: $Exports<'logform/dist/errors'>;
}
declare module 'logform/dist/format.js' {
  declare module.exports: $Exports<'logform/dist/format'>;
}
declare module 'logform/dist/index' {
  declare module.exports: $Exports<'logform/dist'>;
}
declare module 'logform/dist/index.js' {
  declare module.exports: $Exports<'logform/dist'>;
}
declare module 'logform/dist/json.js' {
  declare module.exports: $Exports<'logform/dist/json'>;
}
declare module 'logform/dist/label.js' {
  declare module.exports: $Exports<'logform/dist/label'>;
}
declare module 'logform/dist/levels.js' {
  declare module.exports: $Exports<'logform/dist/levels'>;
}
declare module 'logform/dist/logstash.js' {
  declare module.exports: $Exports<'logform/dist/logstash'>;
}
declare module 'logform/dist/metadata.js' {
  declare module.exports: $Exports<'logform/dist/metadata'>;
}
declare module 'logform/dist/ms.js' {
  declare module.exports: $Exports<'logform/dist/ms'>;
}
declare module 'logform/dist/pad-levels.js' {
  declare module.exports: $Exports<'logform/dist/pad-levels'>;
}
declare module 'logform/dist/pretty-print.js' {
  declare module.exports: $Exports<'logform/dist/pretty-print'>;
}
declare module 'logform/dist/printf.js' {
  declare module.exports: $Exports<'logform/dist/printf'>;
}
declare module 'logform/dist/simple.js' {
  declare module.exports: $Exports<'logform/dist/simple'>;
}
declare module 'logform/dist/splat.js' {
  declare module.exports: $Exports<'logform/dist/splat'>;
}
declare module 'logform/dist/timestamp.js' {
  declare module.exports: $Exports<'logform/dist/timestamp'>;
}
declare module 'logform/dist/uncolorize.js' {
  declare module.exports: $Exports<'logform/dist/uncolorize'>;
}
declare module 'logform/errors.js' {
  declare module.exports: $Exports<'logform/errors'>;
}
declare module 'logform/examples/combine.js' {
  declare module.exports: $Exports<'logform/examples/combine'>;
}
declare module 'logform/examples/filter.js' {
  declare module.exports: $Exports<'logform/examples/filter'>;
}
declare module 'logform/examples/invalid.js' {
  declare module.exports: $Exports<'logform/examples/invalid'>;
}
declare module 'logform/examples/metadata.js' {
  declare module.exports: $Exports<'logform/examples/metadata'>;
}
declare module 'logform/examples/padLevels.js' {
  declare module.exports: $Exports<'logform/examples/padLevels'>;
}
declare module 'logform/examples/volume.js' {
  declare module.exports: $Exports<'logform/examples/volume'>;
}
declare module 'logform/format.js' {
  declare module.exports: $Exports<'logform/format'>;
}
declare module 'logform/index' {
  declare module.exports: $Exports<'logform'>;
}
declare module 'logform/index.js' {
  declare module.exports: $Exports<'logform'>;
}
declare module 'logform/json.js' {
  declare module.exports: $Exports<'logform/json'>;
}
declare module 'logform/label.js' {
  declare module.exports: $Exports<'logform/label'>;
}
declare module 'logform/levels.js' {
  declare module.exports: $Exports<'logform/levels'>;
}
declare module 'logform/logstash.js' {
  declare module.exports: $Exports<'logform/logstash'>;
}
declare module 'logform/metadata.js' {
  declare module.exports: $Exports<'logform/metadata'>;
}
declare module 'logform/ms.js' {
  declare module.exports: $Exports<'logform/ms'>;
}
declare module 'logform/pad-levels.js' {
  declare module.exports: $Exports<'logform/pad-levels'>;
}
declare module 'logform/pretty-print.js' {
  declare module.exports: $Exports<'logform/pretty-print'>;
}
declare module 'logform/printf.js' {
  declare module.exports: $Exports<'logform/printf'>;
}
declare module 'logform/simple.js' {
  declare module.exports: $Exports<'logform/simple'>;
}
declare module 'logform/splat.js' {
  declare module.exports: $Exports<'logform/splat'>;
}
declare module 'logform/timestamp.js' {
  declare module.exports: $Exports<'logform/timestamp'>;
}
declare module 'logform/uncolorize.js' {
  declare module.exports: $Exports<'logform/uncolorize'>;
}
