// flow-typed signature: a4763d8a961d35edb849d5959d097306
// flow-typed version: <<STUB>>/p-queue_v^6.6.2/flow_v0.166.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'p-queue/dist' {
  declare module.exports: any;
}

declare module 'p-queue/dist/lower-bound' {
  declare module.exports: any;
}

declare module 'p-queue/dist/options' {
  declare module.exports: any;
}

declare module 'p-queue/dist/priority-queue' {
  declare module.exports: any;
}

declare module 'p-queue/dist/queue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'p-queue/dist/index' {
  declare module.exports: $Exports<'p-queue/dist'>;
}
declare module 'p-queue/dist/index.js' {
  declare module.exports: $Exports<'p-queue/dist'>;
}
declare module 'p-queue/dist/lower-bound.js' {
  declare module.exports: $Exports<'p-queue/dist/lower-bound'>;
}
declare module 'p-queue/dist/options.js' {
  declare module.exports: $Exports<'p-queue/dist/options'>;
}
declare module 'p-queue/dist/priority-queue.js' {
  declare module.exports: $Exports<'p-queue/dist/priority-queue'>;
}
declare module 'p-queue/dist/queue.js' {
  declare module.exports: $Exports<'p-queue/dist/queue'>;
}
