// flow-typed signature: 8dbb8f1cbecfc276f97945196e8a4fd1
// flow-typed version: <<STUB>>/uWebSockets.js_vhttps://github.com/uNetworking/uWebSockets.js/archive/v20.5.0.tar.gz/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uWebSockets.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uWebSockets.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uWebSockets.js/uws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uWebSockets.js/uws.js' {
  declare module.exports: $Exports<'uWebSockets.js/uws'>;
}
