// flow-typed signature: cce848659c0d674630af4bb952819a1e
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.16.3/flow_v0.166.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
